{% set version = "1.12.0" %}

package:
  name: blosc
  version: {{ version }}

source:
  url: https://github.com/Blosc/c-blosc/archive/v{{ version }}.tar.gz
  sha256: 77ea34f882189f87b68d9b25619462f914f61c8ae152ee5ee5e9971ea36661ec

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - snappy
  run:
    - snappy

test:
  commands:
    - test -e $PREFIX/include/blosc.h                # [unix]
    - test -e $PREFIX/include/blosc-export.h         # [unix]
    - test -e $PREFIX/lib/libblosc.a                 # [unix]
    - test -e $PREFIX/lib/libblosc.dylib             # [osx]
    - test -e $PREFIX/lib/libblosc.so                # [linux]

about:
  home: https://github.com/Blosc/c-blosc
  license: BSD 3-Clause
  license_file: LICENSES/BLOSC.txt
  summary: 'A blocking, shuffling and loss-less compression library that can be faster than `memcpy()`'
  description: |
    Blosc is a high performance compressor optimized for binary data. It has been designed to transmit 
    data to the processor cache faster than the traditional, non-compressed, direct memory fetch approach
    via a memcpy() OS call. Blosc is the first compressor (that I'm aware of) that is meant not only to 
    reduce the size of large datasets on-disk or in-memory, but also to accelerate memory-bound computations.
  doc_url: 
  dev_url: https://github.com/Blosc/c-blosc
  doc_source_url: 

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
