travis:
  secure:
    BINSTAR_TOKEN: q7uG+5bNKnNdneHfGCHXKVz7WivXxGJ70443zEoRw9W1mKVRGzRDE7qmuxj07LaRurTXivcVugcloME8pY4o+Lci5gxVby5FwaofIor/LutTu1cRvVhaWIfiEfLFnsV6SwbEFCKQmdh09whuHcTCqWh46G+LeFjLrQbztdffpmU3n8Ii+uXsBjpC9fCyasrTCEOVPjwEboJ2OwR/57XeYzBR97XgeloNFcPoqPWcQcgrJlTqwbCod9LyKWr9j8i88I5uqN3X6t9yVGT712AJtHfOXXCXMdf7q+YRk+BY0yqgvlA9vyGIpepGj2prq95na0QBav2m6o9zELXhGsuXaZtdPAOC2TD+VwpzkhnAOHNVpkWwUInbOHZTURtFM78CVt68K8N+Mnis7S6fk22F8oQPYqKAnR0jjtJ5c/71WwQvjC2FWRE6ssGOkzqoSXtZxwJRzC+sIVb+LG6dLik3I2MgvWX10itAgoMI08/FZXuoJNP4DtcoRvLLdJwkDvJ3cLlJkXhdUN+R2oiMhyF+4+pC/8p2vzzTNAHEu5WhoDvEPkxsNG6Qdt5935Xfv14gUq07VhnmSAOKmAJglkzeYIlch/9vYmRXLqY/0je8n0163QOIVsHmBPkZ1eMOzXqorTIJ7WTY157VHPNEO14pK+Zj0zSbdyNMYOO5yWHdZpA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
