travis:
  secure:
    BINSTAR_TOKEN: iDeSr6iZ5IR0wKZ7TMDtU9kIW6/xqklF7arq0K+OHpanJWODZ7O1bWDm0v1vhp8NBsTA1sDP4ePPIRLoRYVS7EtWElkj7s6Tg13ZpGvizdnTbdaIEi2C3Mxe7lEM2AoSj0l5NFgp+QaVQqVWp5XHbV0Bk6uethtZi9eLCdzKb9oIRR/Vof8qZ+HYW0U5XvgHvS/uSi/1oclvxG/yKm2fJOqK1zTR4q/xkyISaTOKjRbYtTie6l873NpCqxi5q0H5CNWiTwOwviSZQaVVtqnTcNLqJnX44LFlxCKWG2jrnoVT5iKZuAEaW6zVrhqyKbRbEspaKalz/RVrEYcUrFHwuwwTmGgz8sSmwh0m7CJosMUWa18qDfBZrbnrJISsRGegkJNBTwafDnTigc6x9Qy1ULm//NSPXuL6yCmSgVj63krsUnDwMRZRDwx2ayJtwnG0GMboY4b8B7bcUyw/SG1taJ6FJp1N8ECu1Nd12q4oCXpZKxgSY4kfKaeHixuyIkL6BGlaITrn0/HppLanWSwRMLuj2RenqZCGxytZUjh1WcjV1iFTMo63yvM/vBfHJo8A7QofwDXPbdV1h5JwxMvx+BLPY/+yH9CUkYcNmqpmaYq1qn7nCdLgcz7+/Dfl+dTM7XsCRDT9P69xCpxLvnXqdXw18628L6FLRDvmr/vQN5k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
